# mkdocs.yml

site_name: "L2_MF"
site_url: "https://julienduc-econ.github.io/L2_MF/"

theme:
  name: material  # Requires mkdocs-material
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Include plugins
plugins:
  - search
  - mkdocs-jupyter

# Navigation
nav:
  - Accueil: index.md
  - Intérêts Simples: Interets_simples.ipynb

