site_name: "L2 - Mathématiques financières"
site_url: https://julienduc-econ.github.io/L2_MF/
use_directory_urls: true

theme:
  name: material
  hide:
    site_name: true
  features:
    - navigation.expand  # expands the nav tree

plugins:
  - mkdocs-jupyter

nav:
  - Accueil: index.md
  - Introduction: Intro.md
  - Intérêts simples: Interets_simples.ipynb
  - Intérêts composés: Interets_composes.ipynb
