site_name: L2 - Mathématiques financières
theme:
  name: material
  hide:
    site_name: true

plugins:
  - mkdocs-jupyter

nav:
  - Accueil: index.md
  - Introduction: Intro.md
  - Intérêts simples: Interets_simples.ipynb
  - Intérêts composés: Interets_composes.ipynb
