site_name: L2 - Mathématiques financières
theme:
  name: material
  features:
    - navigation.tabs         # optional, if you want tab navigation
    - navigation.top: false   # THIS hides the top bar site_name

plugins:
  - mkdocs-jupyter

nav:
  - Accueil: index.md
  - Introduction: Intro.md
  - Intérêts simples: Interets_simples.ipynb
  - Intérêts composés: Interets_composes.ipynb

