# mkdocs.yml

site_name: "Mathématiques Financières (L2)"
site_url: "https://julienduc-econ.github.io/L2_MF/"
use_directory_urls: true

theme:
  name: material  # Requires mkdocs-material
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Include plugins
plugins:
  - search
  - mkdocs-jupyter:
      execute: true

# Navigation
nav:
  - Accueil: index.md
  - Introduction: Intro.md
  - Intérêts Simples: Interets_simples.ipynb
  - Valeur Actuelle Nette: VAN.md

