site_name: "L2 - Mathématiques financières"
site_url: https://julienduc-econ.github.io/L2_MF/
use_directory_urls: true

theme:
  name: material

plugins:
  - mkdocs-jupyter:
      execute: true

nav:
  - Accueil: index.md
  - Introduction: Intro.md
  - Intérêts simples: Interets_simples.ipynb